-- Refund return and exchange fields.
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `type` TINYINT DEFAULT 0 COMMENT '售后类型 0-仅退款 1-退货 2-换货';
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `logistics_company` VARCHAR(50) DEFAULT NULL COMMENT '退货物流公司';
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `logistics_no` VARCHAR(50) DEFAULT NULL COMMENT '退货物流单号';
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `return_address` VARCHAR(500) DEFAULT NULL COMMENT '退货地址（JSON格式）';
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `tracking_no` VARCHAR(50) DEFAULT NULL COMMENT '换货物流单号（发出新品）';
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `exchange_product_id` BIGINT DEFAULT NULL COMMENT '换货目标商品ID';
ALTER TABLE `refund` ADD COLUMN IF NOT EXISTS `exchange_sku_id` BIGINT DEFAULT NULL COMMENT '换货目标SKU ID';
