<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getShippingTemplates, removeShippingTemplate, saveShippingTemplate, type ShippingTemplate } from '@/api/shipping'
const rows = ref<ShippingTemplate[]>([]); const visible = ref(false); const editing = ref<ShippingTemplate | null>(null)
const form = reactive<ShippingTemplate>({ name: '', deliveryMethod: 'EXPRESS', regions: '', baseFreight: 0, freeAmount: undefined, status: 1 })
async function load(){ rows.value = await getShippingTemplates() }
function create(){ editing.value=null; Object.assign(form,{name:'',deliveryMethod:'EXPRESS',regions:'',baseFreight:0,freeAmount:undefined,status:1});visible.value=true }
function edit(row:ShippingTemplate){editing.value=row;Object.assign(form,row);visible.value=true}
async function save(){if(!form.name.trim()){ElMessage.warning('请填写模板名称');return}await saveShippingTemplate({...form,id:editing.value?.id});visible.value=false;await load();ElMessage.success('保存成功')}
async function remove(row:ShippingTemplate){await ElMessageBox.confirm('删除后不可恢复，确定继续吗？','删除模板',{type:'warning'});await removeShippingTemplate(row.id!);await load();ElMessage.success('已删除')}
onMounted(load)
</script>
<template><div class="page"><header><h2>配送模板</h2><el-button type="primary" @click="create">新建模板</el-button></header><el-table :data="rows" border><el-table-column prop="name" label="模板名称"/><el-table-column prop="deliveryMethod" label="配送方式" width="130"/><el-table-column prop="regions" label="配送区域"/><el-table-column label="基础运费" width="120"><template #default="{row}">¥{{row.baseFreight.toFixed(2)}}</template></el-table-column><el-table-column label="包邮门槛" width="120"><template #default="{row}">{{row.freeAmount == null ? '-' : `¥${row.freeAmount.toFixed(2)}`}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status === 1 ? 'success' : 'info'">{{row.status === 1 ? '启用' : '停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-dialog v-model="visible" :title="editing?'编辑配送模板':'新建配送模板'" width="500px"><el-form label-width="100px"><el-form-item label="模板名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="配送方式"><el-select v-model="form.deliveryMethod"><el-option label="快递配送" value="EXPRESS"/><el-option label="同城配送" value="LOCAL"/><el-option label="到店自提" value="PICKUP"/></el-select></el-form-item><el-form-item label="配送区域"><el-input v-model="form.regions" placeholder="留空表示全国；多个省份用逗号分隔"/></el-form-item><el-form-item label="基础运费"><el-input-number v-model="form.baseFreight" :min="0" :precision="2"/></el-form-item><el-form-item label="包邮门槛"><el-input-number v-model="form.freeAmount" :min="0" :precision="2"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio :value="1">启用</el-radio><el-radio :value="0">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.page{display:flex;flex-direction:column;gap:16px}header{display:flex;justify-content:space-between;align-items:center}h2{margin:0;font-size:20px}</style>
